spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/songge040701/SpringCloudConfig
          searchPaths: demo_client_config
          username: songge040701@aliyun.com
          password: 19860617b
      label: master
  rabbitmq:
    host: 39.107.98.58
    port: 5672
    username: 
    password: 
  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.107.98.58:8761/eureka/
server:
  port: 8888